from compiler.ins.instruction import Instruction
from compiler.ins.label import Label
from compiler.ins.bin import Bin
from compiler.ins.add import Add
from compiler.ins.andd import And
from compiler.ins.sub import Sub
from compiler.ins.mul import Mul
from compiler.ins.div import Div
from compiler.ins.mod import Mod
from compiler.ins.neg import Neg
from compiler.ins.nott import Not
from compiler.ins.xor import Xor
from compiler.ins.orr import Or
from compiler.ins.sal import Sal
from compiler.ins.sar import Sar
from compiler.ins.lea import Lea
from compiler.ins.cmp import Cmp
from compiler.ins.jmp import Jmp
from compiler.ins.cjump import CJump
from compiler.ins.ret import Return
from compiler.ins.call import Call
from compiler.ins.push import Push
from compiler.ins.pop import Pop
from compiler.ins.move import Move
