from compiler.ir.ir import IR
from compiler.ir.label import Label
from compiler.ir.assign import Assign
from compiler.ir.expr import Expr
from compiler.ir.unary import Unary
from compiler.ir.binary import Binary
from compiler.ir.call import Call
from compiler.ir.ret import Return
from compiler.ir.cjump import CJump
from compiler.ir.jump import Jump
from compiler.ir.intconst import IntConst
from compiler.ir.strconst import StrConst
from compiler.ir.var import Var
from compiler.ir.mem import Mem
from compiler.ir.addr import Addr
